" =========== Выбор стиля синтаксиса =================
syntax on
" molokai можно подключить только когда будет загружен плагин
colorscheme molokai
let g:molokai_original = 1

" ========= Менеджер плагинов Vim-plug ===============
call plug#begin('~/.vim/plugged')
" Файловый менеджер внутри vim
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
" Поддержка русского языка (можно набирать команды на русском)
Plug 'powerman/vim-plugin-ruscmd'
" Красивая и функциональная строка состояния
Plug 'vim-airline/vim-airline'
" Стиль синтаксиса molokai
Plug 'tomasr/molokai'
call plug#end()

" ========= Назначение горячих клавиш ================
" Запуск файлового менеджера внутри vim
map <C-n> :NERDTreeToggle<CR>
