" =========== Выбор стиля синтаксиса =================
syntax on
" molokai можно подключить только когда будет загружен плагин
" и нужно ещё для neovim создать символьную ссылку из папки плагина
" в папку colors
colorscheme molokai
let g:molokai_original = 1

" ========= Менеджер плагинов Vim-plug ===============
call plug#begin('~/.vim/plugged')
" Файловый менеджер внутри vim
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
" Поддержка русского языка (можно набирать команды на русском)
Plug 'powerman/vim-plugin-ruscmd'
" Красивая и функциональная строка состояния
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
" Стиль синтаксиса molokai
Plug 'tomasr/molokai'
" Для ассинхронного make
Plug 'benekastah/neomake'
" Взаимодействие с git
Plug 'tpope/vim-fugitive'
" Делать вставки шаблонов с зависимостями на другие плагины
Plug 'MarcWeber/vim-addon-mw-utils' | Plug 'tomtom/tlib_vim' | Plug 'garbas/vim-snipmate'
Plug 'honza/vim-snippets' " Набор готовых шаблонов (вроде)
" Быстрое перемещение к слову
Plug 'easymotion/vim-easymotion'
" Комментирование
Plug 'tomtom/tcomment_vim'
" Автодополнение (смотреть на github как настраивать)
Plug 'Shougo/deoplete.nvim'
" Относительная нумерация строк
Plug 'numbers.vim'
" Проверка синтаксических ошибок
"Plug 'scrooloose/syntastic'
" Красивое отображение отступов в виде вертикальных линий (кажется не работает TODO)
Plug 'nathanaelkane/vim-indent-guides'
" Удобная работа со встроенным терминалом
Plug 'kassio/neoterm'
" Возможность перехода по частям слова в CamelCase
Plug 'bkad/CamelCaseMotion'
" Автосохранение
Plug '907th/vim-auto-save'
call plug#end()

" ========= Назначение горячих клавиш ================
" Запуск файлового менеджера внутри vim
map <C-n> :NERDTreeToggle<CR>

" ========= Конфигурация редактора ===================
" Замена клавиши esc на jj
:imap jj <Esc>
" Для русской раскладки
:imap оо <Esc>

" Замена табов на пробелы
filetype plugin indent on
" Отображать знак табуляции как 4 пробела
set tabstop=4
" Когда табуляция длиннее 4 пробелов, заменить на 4 пробела (TODO)
set shiftwidth=4
" При нажатии на tab добавить 4 пробела
set expandtab

" Замена <Leader> со стандартного \ на пробел
" больше нужно для более простой работы с easymotion плагином
let mapleader = "\<space>"

" ========= Конфигурация плагинов ====================
" =============== deoplete ===========================
" Использование deoplete при старте
let g:deoplete#enable_at_startup = 1
" Выбор вручную варианты дополнения по tab
inoremap <silent><expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
" После указанного числа символов будую предлагаться варианты
let g:deoplete#auto_completion_start_length = 1

let g:deoplete#enable_ignore_case = 1
let g:deoplete#enable_smart_case = 1
let g:deoplete#enable_camel_case = 1

" =============== easymotion =========================
" Вызов плагина easy motion по одному нажатию на <Leader>
map <Leader> <Plug>(easymotion-prefix)

" =============== neoterm ============================
let g:neoterm_position = 'vertical'
" Комбинация позволяющая привязывать запускающуюся команду по нажатию
let g:neoterm_automap_keys = ',tt'
" Пересылка строки или выделенной области в терминал
nnoremap <silent> <f9> :TREPLSend<cr>
vnoremap <silent> <f9> :TREPLSend<cr>
nnoremap <silent> <f10> :TREPLSendFile<cr>
" Спрятать/закрыть терминал
nnoremap <silent> ,th :call neoterm#close()<cr>

" =============== AutoSave ===========================
let g:auto_save = 1

" =============== camelCase ==========================
" Чтобы начало работать
" Конфликтует с плагином easymotion
"call camelcasemotion#CreateMotionMappings('<leader>')
